title: Tasks
modelClass: AdrisonLuz\NanoTask\Models\Task
list: $/adrisonluz/nanotask/models/task/columns.yaml
recordUrl: 'adrisonluz/nanotask/tasks/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
